'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {browserSessionPersistence,setPersistence,signInWithEmailAndPassword,signOut} from 'firebase/auth';
import {Eye,EyeOff,ArrowRight,LockKeyhole} from 'lucide-react';
import {auth} from '@/lib/firebase';
import {getProfile,canAccess} from '@/lib/roles';
export default function AdminLogin(){
 const router=useRouter();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setError('');setBusy(true);try{if(!auth)throw {code:'auth/not-configured'};await setPersistence(auth,browserSessionPersistence);const result=await signInWithEmailAndPassword(auth,email.trim(),password);const profile=await getProfile(result.user.uid);if(!canAccess(profile)){await signOut(auth);setError('هذا الحساب لا يملك صلاحية الإدارة. تواصل مع مسؤول المشروع.');return;}setPassword('');const next=new URLSearchParams(window.location.search).get('next');const allowed=['/admin','/admin/lands','/admin/requests','/admin/users','/admin/supervisors'];router.replace(next&&allowed.includes(next)?next:'/admin');}catch(e){const code=(e as {code?:string}).code;setError(code==='auth/too-many-requests'?'محاولات كثيرة. يرجى المحاولة لاحقًا.':code==='auth/network-request-failed'?'تعذر الاتصال. تحقق من اتصال الإنترنت.':code==='auth/operation-not-allowed'?'تسجيل الدخول بالبريد وكلمة المرور غير مفعّل في Firebase.':code==='auth/not-configured'?'إعدادات Firebase غير مكتملة.':'تعذر تسجيل الدخول. تحقق من البريد الإلكتروني وكلمة المرور.');}finally{setBusy(false);}}
 return <div className="admin-auth-screen"><div className="admin-auth-card"><Link href="/" aria-label="العودة إلى الرئيسية"><img src="/qarm-logo.svg" alt="قَرم" width="78" height="62"/></Link><span className="auth-eyebrow"><LockKeyhole size={15}/> مساحة الإدارة</span><h1>أهلًا بعودتك</h1><p>سجّل الدخول لإدارة الأراضي ومتابعة طلبات التواصل.</p><form onSubmit={submit}><label>البريد الإلكتروني<input required type="email" autoComplete="username" dir="ltr" value={email} maxLength={254} disabled={busy} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com"/></label><label htmlFor="admin-password">كلمة المرور</label><div className="password-field"><input id="admin-password" required type={visible?'text':'password'} autoComplete="current-password" dir="ltr" value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={visible?'إخفاء كلمة المرور':'إظهار كلمة المرور'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy?'جارٍ تسجيل الدخول…':'تسجيل الدخول'}<ArrowRight size={17}/></button></form><Link href="/" className="auth-back">العودة إلى الموقع</Link></div><span className="auth-footer">قَرم — مساحة لرؤية أكبر</span></div>;
}
