'use client';
import {useEffect,useState,useCallback} from 'react';
import Link from 'next/link';
import {collection,onSnapshot,doc,setDoc} from 'firebase/firestore';
import {ArrowUpLeft,MapPin,Search,LandPlot,ArrowDown,Phone,X,Check,Map as MapIcon,LayoutGrid} from 'lucide-react';
import LandMap from './land-map';
import {db} from '@/lib/firebase';
import {Land,format,samples,displayLandStatus,landStatusClass} from '@/lib/lands';
import {PublicLand,ContactRequest,publicLand,PUBLIC_KEY,REQUESTS_KEY,cloudMode} from '@/lib/public-lands';
export default function PublicMarketplace(){
 const [lands,setLands]=useState<PublicLand[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[region,setRegion]=useState(''),[listingStatus,setListingStatus]=useState('الكل'),[sort,setSort]=useState('default'),[mapView,setMapView]=useState(false),[selected,setSelected]=useState<string|null>(null),[contact,setContact]=useState<PublicLand|null>(null),[name,setName]=useState(''),[phone,setPhone]=useState(''),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[success,setSuccess]=useState(false),[formError,setFormError]=useState('');
 useEffect(()=>{if(cloudMode){if(!db){setError('تعذر الاتصال بخدمة الأراضي.');setLoading(false);return;}return onSnapshot(collection(db,'publicLands'),s=>{setLands(s.docs.map(d=>({...d.data(),id:d.id}) as PublicLand));setLoading(false);},()=>{setError('تعذر تحميل الأراضي. يرجى المحاولة لاحقًا.');setLoading(false);});}const read=()=>{try{const saved=localStorage.getItem(PUBLIC_KEY);setLands(saved?JSON.parse(saved):samples.map(l=>publicLand(l)));}catch{setError('تعذر تحميل الأراضي المحلية.');}setLoading(false);};read();window.addEventListener('storage',read);window.addEventListener('qarm-public-updated',read);return()=>{window.removeEventListener('storage',read);window.removeEventListener('qarm-public-updated',read);};},[]);
 const filtered=lands.filter(l=>l.status!=='مباعة'&&(listingStatus==='الكل'||displayLandStatus(l.status)===listingStatus)&&(!region||l.region===region)&&[l.title,l.location,l.region,l.governorate,l.district].some(v=>v?.includes(query))).sort((a,b)=>sort==='price-low'?a.area*a.price-b.area*b.price:sort==='price-high'?b.area*b.price-a.area*a.price:sort==='area'?b.area-a.area:0);
 const select=useCallback((id:string)=>setSelected(id),[]);
 const chosen=filtered.find(l=>l.id===selected);
 function openContact(land:PublicLand){setContact(land);setSuccess(false);setFormError('');setName('');setPhone('');setMessage('');}
 useEffect(()=>{if(!contact)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!sending)setContact(null);};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',close);};},[contact,sending]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!contact||sending)return;const cleanPhone=phone.trim();if(!name.trim()||!/^\+?[0-9\s()-]{7,25}$/.test(cleanPhone)){setFormError('أدخل الاسم ورقم تواصل صحيحًا.');return;}setSending(true);setFormError('');const request:ContactRequest={id:crypto.randomUUID(),landId:contact.id,landTitle:contact.title,name:name.trim(),phone:cleanPhone,message:message.trim(),createdAt:new Date().toISOString(),status:'جديد',adminUid:contact.adminUid||'',region:contact.region||'',governorate:contact.governorate||''};try{if(cloudMode){if(!db)throw Error();await setDoc(doc(db,'contactRequests',request.id),request);}else{const saved=JSON.parse(localStorage.getItem(REQUESTS_KEY)||'[]');localStorage.setItem(REQUESTS_KEY,JSON.stringify([...saved,request]));}setSuccess(true);}catch{setFormError('تعذر حفظ طلبك. يرجى المحاولة مجددًا.');}finally{setSending(false);}}
 function card(land:PublicLand){return <article className="public-land" key={land.id}><div className="plot-art"><svg viewBox="0 0 400 175" aria-hidden="true"><defs><pattern id={'grid-'+land.id} width="38" height="38" patternUnits="userSpaceOnUse" patternTransform="rotate(-25)"><path d="M38 0H0V38" fill="none" stroke="#d7dfcf" strokeWidth="1"/></pattern></defs><rect width="400" height="175" fill={`url(#grid-${land.id})`}/><path d="M140 57L228 34L269 112L176 143Z" fill="#d4dec9" stroke="#50795d" strokeWidth="2" strokeDasharray="5 4"/><path d="M140 57L228 34L269 112L176 143Z" fill="none" stroke="#779165" strokeWidth="1"/><circle cx="140" cy="57" r="4" fill="#245c4d"/><circle cx="228" cy="34" r="4" fill="#245c4d"/><circle cx="269" cy="112" r="4" fill="#245c4d"/><circle cx="176" cy="143" r="4" fill="#245c4d"/></svg><span className={'badge '+landStatusClass(land.status)}>{displayLandStatus(land.status)}</span><span className="plot-caption">رسم توضيحي</span></div><div className="public-land-body"><p className="location"><MapPin size={14}/>{[land.region,land.district].filter(Boolean).join('، ')||land.location}</p><h3>{land.title}</h3><div className="public-land-numbers"><div><small>المساحة</small><strong>{format(land.area)} <em>م²</em></strong></div><div><small>سعر المتر</small><strong>{format(land.price)} <em>ر.س</em></strong></div></div><div className="public-price"><span>القيمة الإجمالية</span><strong>{format(land.area*land.price)} <small>ر.س</small></strong></div><button className="primary full" onClick={()=>openContact(land)}>طلب تواصل من الفريق <ArrowUpLeft size={17}/></button><button className="public-map-link" onClick={()=>{setSelected(land.id);setMapView(true);document.getElementById('land-results')?.scrollIntoView({behavior:'smooth'});}}><MapPin size={14}/> عرض الموقع على الخريطة</button></div></article>;}
 return <div className="marketplace"><header className="public-header"><Link href="/" aria-label="قَرم الرئيسية"><img src="/qarm-logo.svg" alt="قَرم" width={61} height={49}/></Link><nav><a href="#land-results">استكشف الأراضي</a><a href="#how-it-works">كيف تبدأ؟</a></nav><Link href="/admin" className="admin-link">لوحة الإدارة <ArrowUpLeft size={15}/></Link></header>
 <section className="public-hero"><div className="hero-copy"><span className="public-eyebrow"><i/> أرضك القادمة تبدأ من هنا</span><h1>مساحة لطموحك.<br/><span>وأرض لمستقبلك.</span></h1><p>استكشف الأراضي وتعرّف على مواقعها ومساحاتها وأسعارها.<br/>اختر ما يناسبك، واترك لفريق قَرم خطوة التواصل.</p><a className="primary" href="#land-results">اكتشف الأراضي <ArrowDown size={17}/></a><div className="hero-trust"><span><Check size={15}/> أسعار ومساحات واضحة</span><span><Check size={15}/> تواصل مباشر مع الفريق</span></div></div><div className="hero-terrain" aria-hidden="true"><svg viewBox="0 0 550 420"><defs><pattern id="hero-grid" width="45" height="45" patternUnits="userSpaceOnUse" patternTransform="rotate(-24)"><path d="M45 0H0V45" stroke="#446b4c" strokeWidth=".6" fill="none"/></pattern></defs><rect width="550" height="420" fill="url(#hero-grid)"/><g fill="none" stroke="#6d8b62" opacity=".35">{[0,1,2,3,4,5].map(i=><ellipse key={i} cx="340" cy="240" rx={90+i*24} ry={48+i*22} transform="rotate(-26 340 240)"/>)}</g><path d="M151 145L322 99L402 263L225 316Z" fill="#668055" fillOpacity=".55" stroke="#d1dbb2" strokeWidth="2"/><path d="M151 145L322 99L402 263L225 316Z" fill="none" stroke="#dae3c4" strokeWidth="2" strokeDasharray="6 5"/>{[[151,145],[322,99],[402,263],[225,316]].map(([cx,cy])=><circle key={cx} cx={cx} cy={cy} r="5" fill="#ecedd8"/>)}<path d="M280 164c-17 0-30 13-30 30 0 24 30 46 30 46s30-22 30-46c0-17-13-30-30-30Z" fill="#eef0dc"/><circle cx="280" cy="193" r="10" fill="#426744"/></svg><div className="terrain-label"><LandPlot size={23}/><div><strong>كل أرض، بداية جديدة</strong><small>اكتشف الاحتمالات مع قَرم</small></div><ArrowUpLeft size={23}/></div><span className="terrain-coordinate">QARM · LAND & POSSIBILITY</span></div></section>
 <section className="public-listings" id="land-results"><div className="public-section-head"><div><span className="eyebrow">فرص تستحق أن تكتشفها</span><h2>ابحث عن أرضك القادمة</h2></div><span className="result-count">{filtered.length} أراضٍ متاحة للاستكشاف</span></div><div className="public-filters"><label className="search"><Search size={19}/><input aria-label="البحث عن أرض" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الأرض، المنطقة أو الحي"/></label><select aria-label="المنطقة" value={region} onChange={e=>setRegion(e.target.value)}><option value="">كل المناطق</option>{[...new Set(lands.map(l=>l.region).filter(Boolean))].map(r=><option key={r} value={r}>{r}</option>)}</select><select aria-label="حالة الأرض" value={listingStatus} onChange={e=>setListingStatus(e.target.value)}><option value="الكل">كل الحالات</option><option value="متاحة للبيع">متاحة للبيع</option><option value="متاحة للإيجار">متاحة للإيجار</option><option value="محجوزة">محجوزة</option></select><select aria-label="ترتيب الأراضي" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">الترتيب الافتراضي</option><option value="price-low">السعر: الأقل أولًا</option><option value="price-high">السعر: الأعلى أولًا</option><option value="area">المساحة: الأكبر أولًا</option></select><div className="view-toggle"><button title="البطاقات" aria-pressed={!mapView} className={!mapView?'chosen':''} onClick={()=>setMapView(false)}><LayoutGrid size={19}/></button><button title="الخريطة" aria-pressed={mapView} className={mapView?'chosen':''} onClick={()=>setMapView(true)}><MapIcon size={19}/></button></div></div>{!cloudMode&&<p className="local-notice">معاينة محلية: الأراضي والطلبات متاحة في هذا المتصفح فقط. الطلبات لا تُرسل إلى فريق خارجي.</p>}{error&&<p role="alert">{error}</p>}{loading?<div className="empty">جارٍ تحميل الأراضي…</div>:!filtered.length?<div className="empty"><LandPlot size={38}/><h3>لم نجد أراضي مطابقة</h3><p>جرّب تغيير البحث أو المنطقة.</p></div>:mapView?<div className="public-map-layout"><LandMap lands={filtered.map(l=>({...l,owner:'',phone:'',notes:'',createdAt:''}) as Land)} selected={selected} onSelect={select} drawing={false} path={[]} onPath={()=>{}}/>{chosen?<aside>{card(chosen)}</aside>:<div className="public-map-prompt">اختر حدود أرض على الخريطة لعرض السعر والمساحة وطلب التواصل.</div>}</div>:<div className="public-land-grid">{filtered.map(card)}</div>}</section>
 <section className="public-how" id="how-it-works"><div><span className="eyebrow">من الاستكشاف إلى التواصل</span><h2>خطوتك القادمة، أبسط.</h2><p>نقرّب لك التفاصيل لتختار الأرض الأنسب لك.</p></div>{[['01','استكشف الأراضي','قارن المواقع والمساحات والأسعار.'],['02','اختر الأرض المناسبة','شاهد موقعها على الخريطة وتعرّف على تفاصيلها.'],['03','اطلب تواصل الفريق','اترك رقمك واهتمامك ليتابع الفريق طلبك.']].map(([n,title,description])=><div className="how-step" key={n}><span>{n}</span><h3>{title}</h3><p>{description}</p></div>)}</section><footer className="public-footer"><img src="/qarm-logo.svg" alt="قَرم" width={44} height={35}/><span>مساحة لرؤية أكبر.</span><small>جميع الحقوق محفوظة © قَرم 2026</small></footer>
 {contact&&<div className="modal-backdrop"><div className="modal public-contact" role="dialog" aria-modal="true" aria-label="طلب تواصل من الفريق"><button className="modal-close" title="إغلاق" disabled={sending} onClick={()=>setContact(null)}><X/></button>{success?<div className="contact-success" role="status"><span><Check size={28}/></span><h2>{cloudMode?'تم استلام طلبك':'تم حفظ الطلب التجريبي'}</h2><p>{cloudMode?'يمكن للفريق الآن مراجعة طلبك والتواصل معك على الرقم الذي أدخلته.':'ستجد الطلب في لوحة الإدارة ← طلبات التواصل، في هذا المتصفح فقط. لم يتم إرساله إلى فريق خارجي.'}</p><button className="primary full" onClick={()=>setContact(null)}>العودة للأراضي</button></div>:<form onSubmit={submit}><span className="stat-icon"><Phone/></span><h2>دعنا نتواصل معك</h2><p>أخبرنا كيف نصل إليك بخصوص هذه الأرض.</p><div className="request-land-summary"><strong>{contact.title}</strong><span>{format(contact.area)} م² · {format(contact.area*contact.price)} ر.س</span></div><label>الاسم<input autoFocus required maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="اسمك الكامل"/></label><label>رقم التواصل<input required type="tel" maxLength={25} autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="05xxxxxxxx" dir="ltr"/></label><label>رسالتك للفريق <small>(اختياري)</small><textarea maxLength={1000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="هل لديك استفسار أو وقت مفضل للتواصل؟"/></label><p className="muted">{cloudMode?'بالإرسال، توافق على مشاركة بياناتك مع فريق قَرم للتواصل بخصوص هذه الأرض.':'هذا طلب تجريبي يُحفظ محليًا ويظهر في لوحة الإدارة على نفس المتصفح.'}</p>{formError&&<p role="alert" className="form-error">{formError}</p>}<button className="primary full" disabled={sending}>{sending?'جارٍ حفظ الطلب…':cloudMode?'إرسال طلب التواصل':'حفظ طلب تواصل تجريبي'}<ArrowUpLeft size={17}/></button></form>}</div></div>}
 </div>;
}
