'use client';
import {useEffect,useState} from 'react';
import {collection,doc,onSnapshot,setDoc,updateDoc} from 'firebase/firestore';
import {initializeApp,deleteApp,getApp} from 'firebase/app';
import {initializeAuth,inMemoryPersistence,createUserWithEmailAndPassword,deleteUser,User} from 'firebase/auth';
import {auth,db} from '@/lib/firebase';
import {UsersRound,UserCheck,ShieldCheck,UserX} from 'lucide-react';
import DashboardStats from '@/components/dashboard-stats';
import {UserProfile} from '@/lib/roles';
import RegionCheckboxes from './region-checkboxes';
import {validSupervisorScope} from '@/lib/governorates';
export default function UserManagement(){
 const [me,setMe]=useState<UserProfile|null>(null),[users,setUsers]=useState<UserProfile[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<UserProfile['role']>('editor'),[scope,setScope]=useState<{regions:string[];governorates:Record<string,string[]>}>({regions:[],governorates:{}}),[drafts,setDrafts]=useState<Record<string,{role:UserProfile['role'];regions:string[];governorates:Record<string,string[]>}>>({});
 useEffect(()=>{if(!auth?.currentUser||!db)return;return onSnapshot(doc(db,'users',auth.currentUser.uid),s=>setMe({...s.data(),id:s.id} as UserProfile),()=>setError('تعذر قراءة الصلاحيات.'));},[]);
 useEffect(()=>{if(me?.role!=='admin'||!me.active||!db)return;return onSnapshot(collection(db,'users'),s=>setUsers(s.docs.map(d=>({...d.data(),id:d.id}) as UserProfile)),()=>setError('تعذر تحميل المستخدمين. تحقق من قواعد Firestore.'));},[me]);
 async function add(e:React.FormEvent){e.preventDefault();if(!db||busy)return;if(role==='regional_supervisor'&&!validSupervisorScope(scope.regions,scope.governorates)){setError('اختر محافظة واحدة على الأقل في كل منطقة للمشرف.');return;}setBusy(true);setError('');setMessage('');let app:ReturnType<typeof initializeApp>|undefined;let created:User|undefined;try{app=initializeApp(getApp().options,'user-provision-'+crypto.randomUUID());const secondary=initializeAuth(app,{persistence:inMemoryPersistence});created=(await createUserWithEmailAndPassword(secondary,email.trim(),password)).user;const id=created.uid;await setDoc(doc(db,'users',id),{name:name.trim(),email:email.trim().toLowerCase(),role,regions:role==='regional_supervisor'?scope.regions:[],governorates:role==='regional_supervisor'?scope.governorates:{},active:true});setMessage('تمت إضافة المستخدم وصلاحياته بنجاح.');setName('');setEmail('');setPassword('');setScope({regions:[],governorates:{}});}catch(e){if(created){try{await deleteUser(created);}catch{setError('تم إنشاء حساب الدخول، لكن تعذر حفظ صلاحياته أو إلغاؤه. راجع مسؤول المشروع لإصلاح الحساب بالمعرّف: '+created.uid);return;}}const code=(e as {code?:string}).code;setError(code==='auth/email-already-in-use'?'هذا البريد مستخدم بالفعل. استخدم بريدًا آخر لإنشاء مستخدم جديد.':code==='auth/weak-password'?'كلمة المرور لا تحقق سياسة الأمان للمشروع.':code==='permission-denied'?'لا تملك صلاحية إدارة المستخدمين.':code?'تعذر إضافة المستخدم. تحقق من اتصالك وإعدادات Firebase.':(e as Error).message);}finally{if(app)await deleteApp(app);setBusy(false);}}
 async function change(user:UserProfile,patch:Partial<UserProfile>){if(!db||busy||user.id===me?.id)return;if(patch.role==='regional_supervisor'&&!validSupervisorScope(patch.regions||[],patch.governorates||{})){setError('اختر محافظة واحدة على الأقل في كل منطقة للمشرف.');return;}setBusy(true);setError('');try{await updateDoc(doc(db,'users',user.id),patch);setDrafts(d=>{const next={...d};delete next[user.id];return next;});setMessage('تم تحديث الصلاحيات.');}catch{setError('تعذر تحديث الصلاحيات.');}finally{setBusy(false);}}
 if(!me)return <div className="empty">جارٍ التحقق من الصلاحيات…{error&&<p role="alert">{error}</p>}</div>;
 if(me.role!=='admin'||!me.active)return <div className="empty">إدارة المستخدمين متاحة للمدير فقط.</div>;
 return <><DashboardStats items={[
  {label:'إجمالي المستخدمين',value:users.length,unit:'حساب',foot:'كل حسابات الفريق المسجّلة',icon:UsersRound},
  {label:'الحسابات النشطة',value:users.filter(user=>user.active).length,unit:'حساب',foot:'يمكنها الدخول إلى لوحة الإدارة',icon:UserCheck},
  {label:'مشرفو المناطق',value:users.filter(user=>user.role==='regional_supervisor').length,unit:'مشرف',foot:'بصلاحيات مناطق ومحافظات محددة',icon:ShieldCheck,gold:true},
  {label:'الحسابات المعطلة',value:users.filter(user=>!user.active).length,unit:'حساب',foot:'تم إيقاف وصولها إلى اللوحة',icon:UserX},
 ]}/><section className="requests-panel"><h2>المستخدمون والصلاحيات</h2><p className="muted">المدير يدير المستخدمين، والمحرر يدير أراضيه، ومشرف المنطقة يدير الأراضي وطلبات التواصل ضمن المحافظات المحددة له. تعطيل المستخدم يمنع دخوله للوحة.</p><form className="user-add-form" onSubmit={add}><div className="user-fields"><label>الاسم<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label><label>البريد الإلكتروني<input required type="email" maxLength={254} dir="ltr" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label>كلمة المرور<input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/></label><label>الصلاحية<select value={role} onChange={e=>setRole(e.target.value as UserProfile['role'])} disabled={busy}><option value="editor">محرر</option><option value="regional_supervisor">مشرف منطقة</option><option value="admin">مدير</option></select></label></div>{role==='regional_supervisor'&&<RegionCheckboxes value={scope} onChange={setScope} disabled={busy}/>}<button className="primary" disabled={busy}>{busy?'جارٍ التنفيذ…':'إضافة المستخدم'}</button></form>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}<div className="request-grid">{users.map(u=><article className="request-card" key={u.id}><h3>{u.name||u.email}</h3><p dir="ltr">{u.email}</p><small dir="ltr">{u.id}</small><label>الصلاحية <select aria-label={'صلاحية '+u.email} disabled={busy||u.id===me.id} value={drafts[u.id]?.role||u.role} onChange={e=>setDrafts(d=>({...d,[u.id]:{role:e.target.value as UserProfile['role'],regions:d[u.id]?.regions||u.regions||[],governorates:d[u.id]?.governorates||u.governorates||{}}}))}><option value="admin">مدير</option><option value="editor">محرر</option><option value="regional_supervisor">مشرف منطقة</option></select></label>{(drafts[u.id]?.role||u.role)==='regional_supervisor'&&<RegionCheckboxes value={{regions:drafts[u.id]?.regions||u.regions||[],governorates:drafts[u.id]?.governorates||u.governorates||{}}} disabled={busy||u.id===me.id} onChange={scope=>setDrafts(d=>({...d,[u.id]:{role:d[u.id]?.role||u.role,...scope}}))}/>}<button className="primary full" disabled={busy||u.id===me.id||!drafts[u.id]} onClick={()=>{const draft=drafts[u.id];if(draft)change(u,{role:draft.role,regions:draft.role==='regional_supervisor'?draft.regions:[],governorates:draft.role==='regional_supervisor'?draft.governorates:{}});}}>حفظ الصلاحيات</button><button className="secondary full" disabled={busy||u.id===me.id} onClick={()=>change(u,{active:!u.active})}>{u.active?'تعطيل الوصول':'تفعيل الوصول'}</button>{u.id===me.id&&<p className="muted">حسابك الحالي — لا يمكن تعطيله أو تغيير صلاحيته هنا.</p>}</article>)}</div></section></>;
}
