export type Point = {lat:number;lng:number};
export type LandStatus='متاحة'|'متاحة للبيع'|'متاحة للإيجار'|'محجوزة'|'مباعة';
export const PROPERTY_TYPE_OPTIONS=['أرض','عمارة','مكتب','استوديو','استراحة','بيت','غرفة','مخيم','مستودع','شاليه','كشك','سينما','مواقف سيارات','صراف / بنك','مصنع','مستشفى أو مركز صحي','محطة كهرباء','برج اتصالات','مجمع','برج','فندق','ورشة','مدرسة','محطة','مزرعة'] as const;
export type PropertyType=(typeof PROPERTY_TYPE_OPTIONS)[number];
export const LAND_STATUS_OPTIONS:Exclude<LandStatus,'متاحة'>[]=['متاحة للبيع','متاحة للإيجار','محجوزة','مباعة'];
export function displayLandStatus(status:LandStatus):Exclude<LandStatus,'متاحة'>{return status==='متاحة'?'متاحة للبيع':status;}
export function isAvailableLand(status:LandStatus){return status==='متاحة'||status==='متاحة للبيع'||status==='متاحة للإيجار';}
export function landStatusClass(status:LandStatus){return status==='متاحة للإيجار'?'status-rent':status==='محجوزة'?'status-reserved':status==='مباعة'?'status-sold':'status-sale';}
export type Land = {id:string;title:string;propertyType?:PropertyType;owner:string;phone:string;location:string;region?:string;governorate?:string;district?:string;referredBy?:string;referredByPhone?:string;area:number;price:number;status:LandStatus;notes:string;path:Point[];createdAt:string};
export const format = (n:number) => new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
export function areaOf(path:Point[]) { if(path.length<3)return 0;const r=6378137;let sum=0;for(let i=0;i<path.length;i++){const a=path[i],b=path[(i+1)%path.length];sum+=(b.lng-a.lng)*Math.PI/180*(2+Math.sin(a.lat*Math.PI/180)+Math.sin(b.lat*Math.PI/180));}return Math.round(Math.abs(sum*r*r/2)*100)/100; }
export function validPath(path:Point[]) { if(path.length<3||path.length>100||areaOf(path)<1)return false; const cross=(a:Point,b:Point,c:Point)=>(b.lng-a.lng)*(c.lat-a.lat)-(b.lat-a.lat)*(c.lng-a.lng);for(let i=0;i<path.length;i++){for(let j=i+1;j<path.length;j++){if(j===i+1||(i===0&&j===path.length-1))continue;const a=path[i],b=path[(i+1)%path.length],c=path[j],d=path[(j+1)%path.length];if(cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0)return false;}}return true; }
export const samples:Land[]=[{id:'sample-1',title:'أرض سكنية في حي النرجس',propertyType:'أرض',owner:'محمد العتيبي',phone:'0500000000',location:'الرياض، حي النرجس',area:750,price:2800,status:'متاحة للبيع',notes:'بيانات توضيحية للتجربة فقط',path:[{lat:24.835,lng:46.665},{lat:24.835,lng:46.6653},{lat:24.83525,lng:46.6653},{lat:24.83525,lng:46.665}],createdAt:'2026-09-12'},{id:'sample-2',title:'أرض تجارية على طريق الملك سلمان',propertyType:'أرض',owner:'عبدالله الدوسري',phone:'0500000000',location:'الرياض، حي العارض',area:1200,price:4200,status:'محجوزة',notes:'بيانات توضيحية للتجربة فقط',path:[{lat:24.861,lng:46.625},{lat:24.861,lng:46.6254},{lat:24.8613,lng:46.6254},{lat:24.8613,lng:46.625}],createdAt:'2026-09-11'},{id:'sample-3',title:'أرض سكنية في حي الملقا',propertyType:'أرض',owner:'خالد القحطاني',phone:'0500000000',location:'الرياض، حي الملقا',area:450,price:3100,status:'متاحة للإيجار',notes:'بيانات توضيحية للتجربة فقط',path:[{lat:24.803,lng:46.608},{lat:24.803,lng:46.60825},{lat:24.8032,lng:46.60825},{lat:24.8032,lng:46.608}],createdAt:'2026-09-10'}];
